# This file holds the configs for Sofus. It folllows the yaml standard

# The below url contains supported sites for Sofus.
urlConfig:
  # SANS sitescsacas
  - https://www.sans.org/reading-room/whitepapers/critical/, ParseSANS
  - https://trendmicro.com/en/research, ParseTrendMicro

workerConfig:
  retryInterval: 2