# This file holds the configs for Sofus. It folllows the yaml standard

# The below url contains supported sites for Sofus.
urlConfig:
  SANS:
    - https://www.sans.org/reading-room/whitepapers/critical/
    - https://www.sans.org/reading-room/whitepapers/detection/
    - https://www.sans.org/reading-room/whitepapers/forensics/
    - https://www.sans.org/reading-room/whitepapers/incident/